name: jz_gifimage
description: a gifimage for flutter,for solving gif cannot be controlled speed,progress
version: 1.1.0
author: donglua <huangdonglu@n8n8.cn>
homepage: https://github.com/donglua/jz_gifimage

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3

dev_dependencies:
flutter:

